# Generated by Django 3.2 on 2022-07-12 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoRegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked', models.URLField(max_length=5000)),
                ('date_add', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkRegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked', models.URLField(max_length=5000)),
                ('linked_link', models.CharField(db_index=True, max_length=20)),
                ('date_add', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('limit', models.BooleanField(default=0)),
                ('limited_link', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('secure_link', models.CharField(default=0, max_length=10)),
                ('start_link', models.DateTimeField(blank=True, null=True)),
                ('date_stop', models.DateTimeField(blank=True, null=True)),
                ('how_many_link', models.IntegerField(db_index=True, default=0)),
                ('again_how_many_link', models.IntegerField(db_index=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_check', models.DateTimeField(db_index=True)),
                ('country_check', models.CharField(db_index=True, max_length=100)),
                ('link_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_link', to='elink_index.linkreguser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='linkreguser',
            constraint=models.UniqueConstraint(fields=('linked_link',), name='unique_generate_link'),
        ),
    ]
